version: '3.7'

services:
  calculator-api:
    image: calculator-api
    ports:
      - 80:80

  portainer-api-client:
    image: portainer-api-client

  portainer:
    image: portainer/portainer
    # admin password: piDgeonsR4u!
    command: --admin-password "$$2y$$05$$lqSaAhxN3gYFIiHlaf5tWumiBuWhP5M.6Fmv8PBSuR0nA2mA9pvUe"
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
